name: NYC_Trips_Analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - alembic=1.4.2
  - appdirs=1.4.3
  - asn1crypto=1.3.0
  - brotlipy=0.7.0
  - ca-certificates=2020.4.5.1
  - certifi=2020.4.5.1
  - cffi=1.14.0
  - chardet=3.0.4
  - click=7.1.2
  - cloudpickle=1.4.1
  - configparser=5.0.0
  - cryptography=2.9.2
  - databricks-cli=0.9.1
  - docker-py=4.2.0
  - docker-pycreds=0.4.0
  - entrypoints=0.3
  - flask=1.1.2
  - gitdb=4.0.5
  - gitpython=3.1.2
  - gorilla=0.3.0
  - gunicorn=20.0.4
  - idna=2.9
  - itsdangerous=1.1.0
  - jinja2=2.11.2
  - joblib=0.14.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcxx=10.0.0
  - libffi=3.2.1
  - libgfortran=4.0.0
  - liblapack=3.8.0
  - libopenblas=0.3.9
  - libprotobuf=3.11.4
  - llvm-openmp=10.0.0
  - mako=1.1.0
  - markupsafe=1.1.1
  - mlflow=1.8.0
  - ncurses=6.1
  - numpy=1.18.4
  - openssl=1.1.1g
  - packaging=20.1
  - pandas=1.0.3
  - pip=20.1
  - prometheus_client=0.7.1
  - prometheus_flask_exporter=0.13.0
  - protobuf=3.11.4
  - py4j=0.10.7
  - pycparser=2.20
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pysocks=1.7.1
  - pyspark=2.4.5
  - python=3.7.6
  - python-dateutil=2.8.1
  - python-editor=1.0.4
  - python_abi=3.7
  - pytz=2020.1
  - pyyaml=5.3.1
  - querystring_parser=1.2.4
  - readline=8.0
  - requests=2.23.0
  - scikit-learn=0.22.2.post1
  - scipy=1.4.1
  - setuptools=46.1.3
  - simplejson=3.17.0
  - six=1.14.0
  - smmap=3.0.4
  - sqlalchemy=1.3.13
  - sqlite=3.30.1
  - sqlparse=0.3.1
  - tabulate=0.8.7
  - tk=8.6.10
  - urllib3=1.25.9
  - websocket-client=0.57.0
  - werkzeug=1.0.1
  - wheel=0.34.2
  - xz=5.2.5
  - yaml=0.2.4
  - zlib=1.2.11

